### ISSUE TITLE
order of dimensions

### ISSUE THREAD

**Issue by vsauerland** [IAMconsortium/concordia#27]
In the process of re-mapping gridded carbon emissions I notice differences w.r.t. the order of dimensions between RESCUE scenario input and the reference scenario input.

For files "CO2-em-anthro[...]" we have

in RESCUE scenario: CO2_em_anthro(sector, lat, lon, time)
in reference scenario: CO2_em_anthro(sector, time, lat, lon)
in mod. reference scenario: CO2_em_anthro(time, sector, lat, lon)

For files "CO2-em-AIR-anthro[...]" we have

in RESCUE scenario: CO2_em_AIR_anthro(sector, lat, lon, level, time)
in reference scenario: CO2_em_AIR_anthro(level, time, lat, lon)
in mod. reference scenario: CO2_em_AIR_anthro(time, level, lat, lon)

Might be worth to have variable dimensions in the same order as in SSP scenarios? 
Also, "cdo" commands do not support the 5-dimensional version of variable "CO2_em_AIR_anthro".

**Comment by gidden** [comment]
Hi @vsauerland many thanks for opening the issue. Can you let us know which file(s) you're referring to for:

- reference scenario
- mod. reference scenario

Thanks!

**Comment by vsauerland** [comment]
Yes, but I just wonder if there is corresponding consistency in the order of dimensions in the SSP scenarios provided at [input4MIPs](https://esgf-node.llnl.gov/search/input4mips/)

**Comment by coroa** [comment]
Mostly true, i looked at the `*-input4MIPs_emissions_ScenarioMIP_IAMC-REMIND-MAGPIE-ssp534-over-1-1_gn_201501-210012.nc` files and we get:
- `BC_em_AIR_anthro (time, level, lat, lon)`
- `BC_em_anthro (time, sector, lat, lon)`
- `BC_em_openburning (time, lat, lon)`
- `CH4_em_AIR_anthro (time, level, lat, lon)`
- `CH4_em_anthro (time, sector, lat, lon)`
- `CH4_em_openburning (time, lat, lon)`
- `CO_em_AIR_anthro (time, level, lat, lon)`
- `CO_em_anthro (time, sector, lat, lon)`
- `CO_em_openburning (time, lat, lon)`
- `CO2_em_AIR_anthro (level, time, lat, lon)`
- `CO2_em_anthro (sector, time, lat, lon)` (**only one which does not follow the rule**)
- `H2_em_openburning (time, lat, lon)`
- `NH3_em_AIR_anthro (time, level, lat, lon)`
- `NH3_em_anthro (time, sector, lat, lon)`
- `NH3_em_openburning (time, lat, lon)`
- `NMVOC_em_AIR_anthro (time, level, lat, lon)`
- `NMVOC_em_anthro (time, sector, lat, lon)`
- `NMVOC_em_openburning (time, lat, lon)`
- `NOx_em_AIR_anthro (time, level, lat, lon)`
- `NOx_em_anthro (time, sector, lat, lon)`
- `NOx_em_openburning (time, lat, lon)`
- `OC_em_AIR_anthro (time, level, lat, lon)`
- `OC_em_anthro (time, sector, lat, lon)`
- `OC_em_openburning (time, lat, lon)`
- `SO2_em_AIR_anthro (time, level, lat, lon)`
- `SO2_em_anthro (time, sector, lat, lon)`
- `SO2_em_openburning (time, lat, lon)`
- `VOC_em_AIR_anthro (time, level, lat, lon)`
- `VOC_em_anthro (time, sector, lat, lon)`
- `VOC_em_openburning (time, lat, lon)`

**Comment by coroa** [comment]
Closed as part of #33
