### ISSUE TITLE
Review round 2

### ISSUE THREAD

**Issue by coroa** [IAMconsortium/concordia#29]
# Overview

This is a master issue for testing forcing files for Review Round **2**.

The files can be found on the BSC FTP server at

1. Emissions: `/forcings/emissions/2023-12-08` (from 09.01.2023)
2. LUC: `/forcings/land_use/2023-12-08`

# Process

If you find any issues with the data files provided, please open an issue describing the problem and any proposed solutions:

1. [Issues with emissions files](https://github.com/IAMconsortium/concordia/issues/new?labels=review/round-2,emissions)
2. [Issues with LUC files](https://github.com/IAMconsortium/concordia/issues/new?labels=review/round-2,land-use)

# Changes since round 1

## Land use

- dataset for 1995-2100 in 5-year timesteps for all REMIND-MAgPIE scenarios used for the emissions
- added metadata to nc files
- management.nc: added fulwd, rndwd
- transitions.nc: reporting all LUH variables incl. wood harvest variables
- all transitions are gross transitions
- transitions in 2100 are net-zero gross transitions (to be used for extended (2100-2300) scenarios)
- cover all LUH cells (e.g. Greenland was missing before)

### Gridding

- Updated filenames and netcdf metadata following the structure in CMIP6
- New shipping proxies by MariTeam
- New CDR proxies for DACCS and Industrial CDR
- Fixed harmonisation and downscaling for incomplete proxies
- Fixed F-Gas split regression
- Fixed uniform grid (720x360)

### REMIND

- Update MAgPIE model version number from v4.6.7 to v4.7.0
- Activate timber module in MAgPIE to represent managed forests

**Comment by gidden** [comment]
Closing as review round 2 is closed
