### ISSUE TITLE
Starting date of ESM simulations: 2015 or 2020?

### ISSUE THREAD

**Issue by TimotheeBrgs** [IAMconsortium/concordia#36]
Hello,

The current version (2023-12-08) of emissions files seem to imply 2020 as the starting date for ESM simulations.

What is the starting year that we agreed on for the ESM simulations, 2015 or 2020?

- If 2015, input4MIPs files usually includes the 2015 monthly emissions in addition to 2020. A workaround for the ESM modellers would be to interpolate back from 2014 using the historical/CEDS emissions to generate the 2015-2019 leg.

- If 2020, which SSP should be used as initial conditions from the end of 2019?

Thank you.

**Comment by TimotheeBrgs** [comment]
Hello,

I might have found my answer in a draft: RESCUE provides an extrapolation of CEDS until 2019. Where can we download it for ESM testing?

Thank you.

**Comment by coroa** [comment]
Hi @TimotheeBrgs ,

To address what you are raising, we are including the gridded 2015 emissions also in the next round of gridded scenario files, ie the files we are running our last bits of validation on (and intend to upload to the bsc ftp server this week), will have the following time dimension:

```
CFTimeIndex([2015-01-16 00:00:00, 2015-02-15 00:00:00, 2015-03-16 00:00:00,
             2015-04-16 00:00:00, 2015-05-16 00:00:00, 2015-06-16 00:00:00,
             2015-07-16 00:00:00, 2015-08-16 00:00:00, 2015-09-16 00:00:00,
             2015-10-16 00:00:00,
             ...
             2100-03-16 00:00:00, 2100-04-16 00:00:00, 2100-05-16 00:00:00,
             2100-06-16 00:00:00, 2100-07-16 00:00:00, 2100-08-16 00:00:00,
             2100-09-16 00:00:00, 2100-10-16 00:00:00, 2100-11-16 00:00:00,
             2100-12-16 00:00:00],
            dtype='object', length=120, calendar='noleap', freq=None)
```

ie monthly timesteps for the years 2015, 2020, 2030, 2040, ... 2100 .

**Comment by TimotheeBrgs** [comment]
Hi @coroa, thank you for your prompt and clear answer. This will fix the issue.
